title: Vizbull Blog
description: Building Vizbull in public â€” SaaS, AI, Collage Maker
url: "https://vizbull.github.io"
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
permalink: /:title/

